import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.content = m.top.findNode("content")
    m.videoControls = m.top.findNode("videoControls")
    m.focusIndex = 4

    cursorColor = chainLookupReturn(m.global.session, "user.settings.colorCursor", ColorPalette.HIGHLIGHT)

    ' listen for escape events from each button to handle focus movement
    children = m.videoControls.getChildren(-1, 0)
    for each child in children
        child.observeField("escape", "onButtonEscape")
        child.focusBackground = cursorColor
    end for
end sub

sub setButtonFocus(index as integer)
    prevBtn = m.videoControls.getChild(m.focusIndex)
    if prevBtn <> invalid
        prevBtn.focus = false
    end if

    m.focusIndex = index
    btn = m.videoControls.getChild(m.focusIndex)
    btn.focus = true ' estado visual (tu campo custom)
    btn.setFocus(true) ' foco REAL -> aquí es donde llegan las teclas
end sub

sub onButtonEscape(event as object)
    direction = event.getData()

    newIndex = m.focusIndex
    if direction = "right"
        newIndex = m.focusIndex + 1
    else if direction = "left"
        newIndex = m.focusIndex - 1
    end if
    ' up/down: aquí decides si sales del ButtonGroup hacia otro elemento del OSD

    if newIndex >= 0 and newIndex < m.videoControls.getChildCount()
        setButtonFocus(newIndex)
    end if
end sub

sub focusDefaultButton()
    setButtonFocus(m.focusIndex)
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    if not press then return false

    if key = "OK"
        m.top.action = "show"
        return true
    end if

    if key = "back"
        m.top.action = "hide"
        return true
    end if

    return false
end function
