import "pkg:/source/enums/SubtitleSelection.bs"
import "pkg:/source/enums/TaskControl.bs"
import "pkg:/source/enums/VideoControl.bs"
import "pkg:/source/utils/misc.bs"

sub init()

    m.top.observeField("state", "onPlayerStateChanged")

    currentItem = m.global.queueManager.callFunc("getCurrentItem")

    m.LoadMetaDataTask = CreateObject("roSGNode", "LoadVideoContentTask")

    m.LoadMetaDataTask.selectedSubtitleIndex = SubtitleSelection.NOTSET
    m.LoadMetaDataTask.itemId = currentItem.id
    m.LoadMetaDataTask.itemType = currentItem.type
    m.LoadMetaDataTask.selectedAudioStreamIndex = currentItem.selectedAudioStreamIndex

    m.LoadMetaDataTask.observeField("content", "onVideoContentLoaded")

    m.LoadMetaDataTask.control = TaskControl.RUN

    m.osd = m.top.findNode("osd")

end sub

sub onVideoContentLoaded()

    print "OcelotlPlayer content loaded"

    videoContent = m.LoadMetaDataTask.content

    if isValid(videoContent) and videoContent.count() > 0

        m.top.content = videoContent[0].content

        print "OcelotlPlayer PLAY"

        m.top.setFocus(true)
        m.top.control = VideoControl.PLAY

    end if

end sub

sub onOSDAction()

    if m.osd.action = "show"
        showOSD()
    else if m.osd.action = "hide"
        hideOSD()
    end if

end sub


sub onPlayerStateChanged()



end sub


sub showOSD()

    if isValid(m.osd)
        m.osd.callFunc("show")
    end if

end sub


sub hideOSD()

    if isValid(m.osd)
        m.osd.callFunc("hide")
    end if

end sub

function onKeyEvent(key as string, press as boolean) as boolean

    if press and key = "OK"
        if m.osd.visible
            m.osd.visible = false
        else
            m.osd.visible = true
        end if
        return true
    end if

    return false

end function
