import "pkg:/source/utils/misc.bs"

sub init()

    m.osd = m.top.findNode("osd")

    m.top.observeField("state", "onPlayerStateChanged")

    m.osd.observeField("action", "onOSDAction")

end sub


sub onOSDAction()

    if m.osd.action = "show"
        showOSD()
    else if m.osd.action = "hide"
        hideOSD()
    end if

end sub


sub onPlayerStateChanged()

    if isValid(m.osd)
        m.osd.playbackState = m.top.state
    end if

end sub


sub showOSD()

    if isValid(m.osd)
        m.osd.callFunc("show")
    end if

end sub


sub hideOSD()

    if isValid(m.osd)
        m.osd.callFunc("hide")
    end if

end sub
