import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"

const LOGO_RIGHT_PADDING = 30

sub init()

    findNodes()
    initFields()
    m.top.observeField("logoImage", "onLogoImageChanged")

end sub


sub findNodes()

    m.logoImage = m.top.findNode("logoImage")
    m.titleLabel = m.top.findNode("titleLabel")
    m.subtitleLabel = m.top.findNode("subtitleLabel")

end sub

sub initFields()

    m.titleLabel.text = "Prueba Ocelotl Player"
    m.subtitleLabel.text = "Subtitulo de prueba"


    m.titleLabel.color = chainLookupReturn(m.global.session, "user.settings.colorText", ColorPalette.TEXT_PRIMARY)
    m.subtitleLabel.color = chainLookupReturn(m.global.session, "user.settings.colorSubText", ColorPalette.TEXT_SECONDARY)

end sub


sub onPlaybackStateChanged()

    print "OcelotlPlayerOSD state: "; m.top.playbackState

end sub


sub onControlAction()

    if m.controls.action <> ""
        m.top.action = m.controls.action
    end if

end sub

sub show()

    m.top.visible = true

end sub


sub hide()

    m.top.visible = false

end sub

' onLogoLoadStatusChanged: Handler for changes to logo image's status.
'
' @param {dynamic} event - field change event
sub onLogoLoadStatusChanged(event)
    if LCase(event.GetData()) = "ready"
        logoImage = event.getRoSGNode()
        logoImage.unobserveField("loadStatus")
    end if
end sub

' onLogoImageChanged: Handler for changes to m.top.logoImage param.
'
sub onLogoImageChanged()
    if isValidAndNotEmpty(m.top.logoImage)
        logoImage = createObject("roSGNode", "Poster")
        logoImage.Id = "logoImage"
        logoImage.observeField("loadStatus", "onLogoLoadStatusChanged")
        logoImage.uri = m.top.logoImage
        logoImage.translation = [103, 61]
        m.top.appendChild(logoImage)
    end if
end sub
