sub init()

    m.content = m.top.findNode("content")
    m.controls = m.top.findNode("controls")

    m.top.observeField("playbackState", "onPlaybackStateChanged")
    m.controls.observeField("action", "onControlAction")

end sub


sub onPlaybackStateChanged()

    print "OcelotlPlayerOSD state: "; m.top.playbackState

end sub


sub onControlAction()

    if m.controls.action <> ""
        m.top.action = m.controls.action
    end if

end sub

sub show()

    m.top.visible = true

end sub


sub hide()

    m.top.visible = false

end sub
