import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.poster = m.top.findNode("poster")
    m.name = m.top.findNode("name")
    m.trash = m.top.findNode("trash")
    m.baseUrl = m.top.findNode("baseUrl")
    m.labels = m.top.findNode("labels")

    setTextColor()
end sub

sub itemContentChanged()
    server = m.top.itemContent
    m.poster.uri = server.iconUrl
    m.name.text = server.name
    m.baseUrl.text = server.baseUrl

    setTrashIconVisibility()
    setDeleteFocus()
end sub

sub setTrashIconVisibility()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.isSavedServer) then return

    m.trash.visible = m.top.itemContent.isSavedServer
end sub

sub onItemHasFocusChange()
    if not m.top.itemHasFocus
        m.top.itemContent.itemHasDeleteFocus = false
    end if

    setDeleteFocus()
end sub

sub setDeleteFocus()
    if not isValid(m.top.itemContent) then return
    if not isValid(m.top.itemContent.itemHasDeleteFocus) then return

    if m.top.itemHasFocus and m.top.itemContent.itemHasDeleteFocus
        trashColor = ColorPalette.RED
    else
        trashColor = ColorPalette.WHITE
    end if

    m.trash.blendColor = trashColor
end sub

sub setTextColor()
    textColor = ColorPalette.WHITE

    children = m.labels.getChildren(-1, 0)
    for each child in children
        child.color = textColor
    end for
end sub
