import "pkg:/source/enums/ColorPalette.bs"
import "pkg:/source/enums/KeyCode.bs"
import "pkg:/source/enums/TaskControl.bs"
import "pkg:/source/utils/config.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.top.optionsAvailable = false
    m.top.setFocus(true)

    m.serverPicker = m.top.findNode("serverPicker")
    m.serverPicker.focusBitmapUri = "pkg:/images/ocelotl/ui/panels/server_panel.9.png"
    m.serverPicker.focusBitmapBlendColor = ColorPalette.HIGHLIGHT

    m.serverUrlTextbox = m.top.findNode("serverUrlTextbox")
    m.serverUrlContainer = m.top.findNode("serverUrlContainer")
    m.serverPickerContainer = m.top.findNode("serverPickerContainer")

    m.serverPickerContainer.blendColor = ColorPalette.ELEMENTBACKGROUND
    m.serverUrlContainer.blendColor = ColorPalette.ELEMENTBACKGROUND

    m.submit = m.top.findNode("submit")
    m.submit.background = ColorPalette.SMOKE
    m.submit.color = ColorPalette.WHITE
    m.submit.focusBackground = ColorPalette.HIGHLIGHT
    m.submit.focusColor = ColorPalette.WHITE

    m.top.observeField("serverUrl", "clearErrorMessage")

    ScanForServers()
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    if not press then return false

    group = m.global.sceneManager.callFunc("getActiveScene")

    if key = KeyCode.RIGHT and m.serverPicker.isInFocusChain()
        selectedServer = m.serverPicker.content.getChild(m.serverPicker.itemFocused)
        if chainLookupReturn(selectedServer, "isSavedServer", false)
            selectedServer.itemHasDeleteFocus = true
            return true
        end if
        return false
    end if

    if key = KeyCode.LEFT and m.serverPicker.isInFocusChain()
        selectedServer = m.serverPicker.content.getChild(m.serverPicker.itemFocused)
        if isValid(selectedServer)
            selectedServer.itemHasDeleteFocus = false
        end if
        return true
    end if

    if key = KeyCode.OK
        if m.serverPicker.isInFocusChain()
            selectedServer = m.serverPicker.content.getChild(m.serverPicker.itemFocused)

            if chainLookupReturn(selectedServer, "itemHasDeleteFocus", false)
                m.top.forgetServer = selectedServer.baseUrl
                return true
            end if

            m.top.serverUrl = selectedServer.baseUrl

            m.submit.setFocus(true)
            m.submit.focus = true
            group.lastFocus = m.submit
            return true
        end if

        if m.submit.hasFocus()
            m.submit.selected = not m.submit.selected
            return true
        end if

        if m.serverUrlContainer.isInFocusChain()
            ShowKeyboard()
            return true
        end if

        return false
    end if

    if key = KeyCode.DOWN
        if m.serverPicker.isInFocusChain() and m.serverPicker.content.getChildCount() > 0 and m.serverPicker.itemFocused = m.serverPicker.content.getChildCount() - 1
            m.serverUrlContainer.setFocus(true)
            m.serverUrlContainer.blendColor = ColorPalette.HIGHLIGHT
            group.lastFocus = m.serverUrlContainer
            return true
        end if

        if m.serverUrlContainer.isInFocusChain()
            m.serverUrlContainer.blendColor = ColorPalette.ELEMENTBACKGROUND
            m.submit.setFocus(true)
            m.submit.focus = true
            group.lastFocus = m.submit
            return true
        end if

        return false
    end if

    if key = KeyCode.UP
        if m.serverUrlContainer.isInFocusChain() and isValidAndNotEmpty(m.servers)
            m.serverPicker.setFocus(true)
            m.serverUrlContainer.blendColor = ColorPalette.ELEMENTBACKGROUND
            group.lastFocus = m.serverPicker
            return true
        end if

        if m.serverUrlContainer.isInFocusChain() and m.servers.Count() = 0
            ScanForServers()
            m.serverUrlContainer.blendColor = ColorPalette.ELEMENTBACKGROUND
            return true
        end if

        if m.submit.hasFocus()
            m.submit.focus = false

            m.serverUrlContainer.setFocus(true)
            m.serverUrlContainer.blendColor = ColorPalette.HIGHLIGHT
            group.lastFocus = m.serverUrlContainer
            return true
        end if

        return false
    end if

    if key = KeyCode.BACK
        if m.serverUrlContainer.isInFocusChain() and isValidAndNotEmpty(m.servers)
            m.serverUrlContainer.blendColor = ColorPalette.ELEMENTBACKGROUND

            m.serverPicker.setFocus(true)
            group.lastFocus = m.serverPicker
            return true
        end if

        if m.submit.hasFocus() and isValidAndNotEmpty(m.servers)
            m.submit.focus = false

            m.serverPicker.setFocus(true)
            group.lastFocus = m.serverPicker
            return true
        end if

        if m.submit.hasFocus() and m.servers.Count() = 0
            m.submit.focus = false

            m.serverUrlContainer.blendColor = ColorPalette.HIGHLIGHT
            m.serverUrlContainer.setFocus(true)
            group.lastFocus = m.serverUrlContainer
            return true
        end if

        if m.serverUrlContainer.isInFocusChain() and m.servers.Count() = 0
            ScanForServers()
            return true
        end if

        if m.serverPicker.isInFocusChain() and isValidAndNotEmpty(m.servers)
            ScanForServers()
            return true
        end if

        return false
    end if

    return false
end function

sub ScanForServers()
    m.ssdpScanner = CreateObject("roSGNode", "ServerDiscoveryTask")
    m.ssdpScanner.observeField("content", "ScanForServersComplete")
    m.ssdpScanner.control = TaskControl.RUN
    startLoadingSpinner(false)
end sub

sub ScanForServersComplete(event)
    m.servers = event.getData()

    items = CreateObject("roSGNode", "ServerData")
    for each server in m.servers
        server.isSavedServer = false
        server.subtype = "ServerData"
        'add new fields for every server property onto the ContentNode (rather than making a dedicated component just to hold data...)
        items.update([server], true)
    end for

    'load any previously logged in to servers as well (if they aren't already discovered on the local network)
    saved = get_setting("saved_servers")
    if isValid(saved)
        savedServers = ParseJson(saved)
        for each server in savedServers.serverList
            alreadyListed = false
            for each listed in m.servers
                if LCase(listed.baseUrl) = server.baseUrl 'saved server data is always lowercase
                    alreadyListed = true
                    exit for
                end if
            end for
            if alreadyListed = false
                server.isSavedServer = true
                items.update([server], true)
                m.servers.push(server)
            end if
        end for
    end if

    m.serverPicker.content = items
    stopLoadingSpinner()

    group = m.global.sceneManager.callFunc("getActiveScene")

    'if we have at least one server, focus on the server picker
    if m.servers.Count() > 0
        m.serverPicker.setFocus(true)
        group.lastFocus = m.serverPicker
        'no servers found...focus on the input textbox
    else
        m.serverUrlContainer.setFocus(true)
        m.serverUrlContainer.blendColor = ColorPalette.HIGHLIGHT
        group.lastFocus = m.serverUrlContainer
    end if

end sub

sub ShowKeyboard()
    dialog = createObject("roSGNode", "StandardKeyboardDialog")
    dialog.title = tr("Enter the server name or ip address")
    dialog.buttons = [tr("OK"), tr("Cancel")]
    dialog.text = m.serverUrlTextbox.text

    palette = createObject("roSGNode", "RSGPalette")
    palette.colors = { DialogBackgroundColor: ColorPalette.ELEMENTBACKGROUND }
    dialog.palette = palette

    m.top.getscene().dialog = dialog
    m.dialog = dialog

    dialog.observeField("buttonSelected", "onDialogButton")
end sub

function onDialogButton()
    d = m.dialog
    button_text = d.buttons[d.buttonSelected]

    if button_text = tr("OK")
        m.serverUrlTextbox.text = d.text
        m.dialog.close = true
        return true
    else if button_text = tr("Cancel")
        m.dialog.close = true
        return true
    else
        return false
    end if
end function

sub clearErrorMessage()
    m.top.errorMessage = ""
end sub
