import "pkg:/source/utils/misc.bs"

sub init()
    m.videoControls = m.top.findNode("videoControls")
    m.videoControls.observeField("action", "onVideoControlsAction")
end sub

sub onVideoControlsAction(event as object)
    m.top.action = event.getData()
end sub

sub onIsPlayingChanged()
    m.videoControls.isPlaying = m.top.isPlaying
end sub

sub focusControls()
    m.videoControls.callFunc("focusControls")
end sub
